import axios from "axios";

const BACKEND_URL = process.env.REACT_APP_BACKEND_URL;
export const API = `${BACKEND_URL}/api`;

const http = axios.create({ baseURL: API });

export const api = {
  employees: () => http.get("/employees").then((r) => r.data),
  segmentOptions: () => http.get("/segments/options").then((r) => r.data),
  categoryTypes: () => http.get("/category-types").then((r) => r.data),

  categories: () => http.get("/categories").then((r) => r.data),
  createCategory: (d) => http.post("/categories", d).then((r) => r.data),
  updateCategory: (id, d) => http.put(`/categories/${id}`, d).then((r) => r.data),
  deleteCategory: (id) => http.delete(`/categories/${id}`).then((r) => r.data),
  reorderCategories: (ids) => http.post("/categories/reorder", { ordered_ids: ids }).then((r) => r.data),

  subcategories: (categoryId) =>
    http.get("/subcategories", { params: categoryId ? { category_id: categoryId } : {} }).then((r) => r.data),
  createSubcategory: (d) => http.post("/subcategories", d).then((r) => r.data),
  updateSubcategory: (id, d) => http.put(`/subcategories/${id}`, d).then((r) => r.data),
  deleteSubcategory: (id) => http.delete(`/subcategories/${id}`).then((r) => r.data),

  announcements: (params) => http.get("/announcements", { params }).then((r) => r.data),
  feed: (employeeId) => http.get("/announcements/feed", { params: { employee_id: employeeId } }).then((r) => r.data),
  announcement: (id) => http.get(`/announcements/${id}`).then((r) => r.data),
  createAnnouncement: (d) => http.post("/announcements", d).then((r) => r.data),
  updateAnnouncement: (id, d) => http.put(`/announcements/${id}`, d).then((r) => r.data),
  approveAnnouncement: (id) => http.post(`/announcements/${id}/approve`).then((r) => r.data),
  rejectAnnouncement: (id) => http.post(`/announcements/${id}/reject`).then((r) => r.data),
  pinAnnouncement: (id) => http.post(`/announcements/${id}/pin`).then((r) => r.data),
  deleteAnnouncement: (id) => http.delete(`/announcements/${id}`).then((r) => r.data),

  pulses: () => http.get("/pulses").then((r) => r.data),
  pulseFeed: (employeeId) => http.get("/pulses/feed", { params: { employee_id: employeeId } }).then((r) => r.data),
  pulse: (id) => http.get(`/pulses/${id}`).then((r) => r.data),
  createPulse: (d) => http.post("/pulses", d).then((r) => r.data),
  updatePulse: (id, d) => http.put(`/pulses/${id}`, d).then((r) => r.data),
  deletePulse: (id) => http.delete(`/pulses/${id}`).then((r) => r.data),
  respondPulse: (id, d) => http.post(`/pulses/${id}/respond`, d).then((r) => r.data),
  pulseReport: (id) => http.get(`/pulses/${id}/report`).then((r) => r.data),
  pulseMyHistory: (id, employeeId) => http.get(`/pulses/${id}/my-history`, { params: { employee_id: employeeId } }).then((r) => r.data),
  pulseCompare: (id, params) => http.get(`/pulses/${id}/compare`, { params }).then((r) => r.data),

  events: () => http.get("/events").then((r) => r.data),
  eventFeed: (employeeId) => http.get("/events/feed", { params: { employee_id: employeeId } }).then((r) => r.data),
  event: (id, employeeId) => http.get(`/events/${id}`, { params: employeeId ? { employee_id: employeeId } : {} }).then((r) => r.data),
  createEvent: (d) => http.post("/events", d).then((r) => r.data),
  updateEvent: (id, d) => http.put(`/events/${id}`, d).then((r) => r.data),
  deleteEvent: (id) => http.delete(`/events/${id}`).then((r) => r.data),
  rsvpEvent: (id, d) => http.post(`/events/${id}/rsvp`, d).then((r) => r.data),
  eventReport: (id) => http.get(`/events/${id}/report`).then((r) => r.data),

  moodConfig: () => http.get("/mood/config").then((r) => r.data),
  updateMoodConfig: (d) => http.put("/mood/config", d).then((r) => r.data),
  moodToday: (employeeId) => http.get("/mood/today", { params: { employee_id: employeeId } }).then((r) => r.data),
  submitMood: (d) => http.post("/mood/entry", d).then((r) => r.data),
  moodMyHistory: (employeeId) => http.get("/mood/my-history", { params: { employee_id: employeeId } }).then((r) => r.data),
  moodReport: (department) => http.get("/mood/report", { params: department ? { department } : {} }).then((r) => r.data),

  listingsConfig: () => http.get("/listings/config").then((r) => r.data),
  updateListingsConfig: (d) => http.put("/listings/config", d).then((r) => r.data),
  listings: (params) => http.get("/listings", { params }).then((r) => r.data),
  listingsFeed: (employeeId, type) => http.get("/listings/feed", { params: { employee_id: employeeId, ...(type ? { type } : {}) } }).then((r) => r.data),
  myListings: (employeeId) => http.get("/listings/mine", { params: { employee_id: employeeId } }).then((r) => r.data),
  listing: (id) => http.get(`/listings/${id}`).then((r) => r.data),
  createListing: (d) => http.post("/listings", d).then((r) => r.data),
  approveListing: (id) => http.post(`/listings/${id}/approve`).then((r) => r.data),
  rejectListing: (id) => http.post(`/listings/${id}/reject`).then((r) => r.data),
  closeListing: (id) => http.post(`/listings/${id}/close`).then((r) => r.data),
  deleteListing: (id) => http.delete(`/listings/${id}`).then((r) => r.data),

  avatarConfig: () => http.get("/avatar/config").then((r) => r.data),
  concepts: () => http.get("/avatar/concepts").then((r) => r.data),
  createConcept: (d) => http.post("/avatar/concepts", d).then((r) => r.data),
  updateConcept: (id, d) => http.put(`/avatar/concepts/${id}`, d).then((r) => r.data),
  deleteConcept: (id) => http.delete(`/avatar/concepts/${id}`).then((r) => r.data),
  addAvatar: (id) => http.post(`/avatar/concepts/${id}/add`).then((r) => r.data),
  removeAvatar: (id, avatar) => http.post(`/avatar/concepts/${id}/remove`, { avatar }).then((r) => r.data),
  conceptsFeed: (employeeId) => http.get("/avatar/concepts/feed", { params: { employee_id: employeeId } }).then((r) => r.data),
  selectAvatar: (d) => http.post("/avatar/select", d).then((r) => r.data),
  avatarReport: () => http.get("/avatar/report").then((r) => r.data),

  routes: () => http.get("/routes").then((r) => r.data),
  routesFeed: (employeeId, city) => http.get("/routes/feed", { params: { employee_id: employeeId, ...(city ? { city } : {}) } }).then((r) => r.data),
  routeCities: () => http.get("/routes/cities").then((r) => r.data),
  route: (id, employeeId) => http.get(`/routes/${id}`, { params: employeeId ? { employee_id: employeeId } : {} }).then((r) => r.data),
  createRoute: (d) => http.post("/routes", d).then((r) => r.data),
  updateRoute: (id, d) => http.put(`/routes/${id}`, d).then((r) => r.data),
  deleteRoute: (id) => http.delete(`/routes/${id}`).then((r) => r.data),
  registerRoute: (id, d) => http.post(`/routes/${id}/register`, d).then((r) => r.data),
  unregisterRoute: (id, d) => http.post(`/routes/${id}/unregister`, d).then((r) => r.data),
  routesReport: () => http.get("/routes/report").then((r) => r.data),

  audiences: () => http.get("/audiences").then((r) => r.data),
  createAudience: (d) => http.post("/audiences", d).then((r) => r.data),
  updateAudience: (id, d) => http.put(`/audiences/${id}`, d).then((r) => r.data),
  deleteAudience: (id) => http.delete(`/audiences/${id}`).then((r) => r.data),
  previewAudience: (d) => http.post("/audiences/preview", d).then((r) => r.data),

  notifications: (kind) => http.get("/notifications", { params: { kind } }).then((r) => r.data),
  createNotification: (d) => http.post("/notifications", d).then((r) => r.data),
  notificationsFeed: (employeeId) => http.get("/notifications/feed", { params: { employee_id: employeeId } }).then((r) => r.data),
  respondNotification: (id, d) => http.post(`/notifications/${id}/respond`, d).then((r) => r.data),
  notificationReport: (id) => http.get(`/notifications/${id}/report`).then((r) => r.data),
  deleteNotification: (id) => http.delete(`/notifications/${id}`).then((r) => r.data),

  hapTopics: () => http.get("/hapbilgi/topics").then((r) => r.data),
  createHapTopic: (d) => http.post("/hapbilgi/topics", d).then((r) => r.data),
  deleteHapTopic: (id) => http.delete(`/hapbilgi/topics/${id}`).then((r) => r.data),
  hapPosts: () => http.get("/hapbilgi/posts").then((r) => r.data),
  createHapPost: (d) => http.post("/hapbilgi/posts", d).then((r) => r.data),
  deleteHapPost: (id) => http.delete(`/hapbilgi/posts/${id}`).then((r) => r.data),
  hapFeed: (employeeId, topicId) => http.get("/hapbilgi/feed", { params: { employee_id: employeeId, ...(topicId ? { topic_id: topicId } : {}) } }).then((r) => r.data),
  likeHapPost: (id, employeeId) => http.post(`/hapbilgi/posts/${id}/like`, { employee_id: employeeId }).then((r) => r.data),

  discCats: () => http.get("/discounts/categories").then((r) => r.data),
  createDiscCat: (d) => http.post("/discounts/categories", d).then((r) => r.data),
  deleteDiscCat: (id) => http.delete(`/discounts/categories/${id}`).then((r) => r.data),
  discounts: () => http.get("/discounts").then((r) => r.data),
  createDiscount: (d) => http.post("/discounts", d).then((r) => r.data),
  deleteDiscount: (id) => http.delete(`/discounts/${id}`).then((r) => r.data),
  discountsFeed: (employeeId, categoryId) => http.get("/discounts/feed", { params: { employee_id: employeeId, ...(categoryId ? { category_id: categoryId } : {}) } }).then((r) => r.data),

  canteens: () => http.get("/canteens").then((r) => r.data),
  createCanteen: (d) => http.post("/canteens", d).then((r) => r.data),
  updateCanteen: (id, d) => http.put(`/canteens/${id}`, d).then((r) => r.data),
  deleteCanteen: (id) => http.delete(`/canteens/${id}`).then((r) => r.data),
  canteensFeed: (employeeId) => http.get("/canteens/feed", { params: { employee_id: employeeId } }).then((r) => r.data),

  hapReact: (id, employeeId, emoji) => http.post(`/hapbilgi/posts/${id}/react`, { employee_id: employeeId, emoji }).then((r) => r.data),

  isgConfig: () => http.get("/isg-ramak/config").then((r) => r.data),
  updateIsgConfig: (d) => http.put("/isg-ramak/config", d).then((r) => r.data),
  createRamak: (d) => http.post("/isg-ramak/reports", d).then((r) => r.data),
  ramakReports: () => http.get("/isg-ramak/reports").then((r) => r.data),
  updateRamakStatus: (id, status) => http.put(`/isg-ramak/reports/${id}/status`, { status }).then((r) => r.data),
  ramakMy: (employeeId) => http.get("/isg-ramak/my", { params: { employee_id: employeeId } }).then((r) => r.data),

  rooms: () => http.get("/rooms").then((r) => r.data),
  createRoom: (d) => http.post("/rooms", d).then((r) => r.data),
  updateRoom: (id, d) => http.put(`/rooms/${id}`, d).then((r) => r.data),
  deleteRoom: (id) => http.delete(`/rooms/${id}`).then((r) => r.data),
  roomsFeed: (employeeId) => http.get("/rooms/feed", { params: { employee_id: employeeId } }).then((r) => r.data),
  roomsReport: () => http.get("/rooms/report").then((r) => r.data),
  createReservation: (d) => http.post("/reservations", d).then((r) => r.data),
  reservations: (params) => http.get("/reservations", { params }).then((r) => r.data),
  cancelReservation: (id) => http.post(`/reservations/${id}/cancel`).then((r) => r.data),
  reservationStatus: (id, status) => http.put(`/reservations/${id}/status`, { status }).then((r) => r.data),

  checkinEvent: (id, employeeId) => http.post(`/events/${id}/checkin`, { employee_id: employeeId }).then((r) => r.data),
  awards: () => http.get("/awards").then((r) => r.data),
  createAward: (d) => http.post("/awards", d).then((r) => r.data),
  deleteAward: (id) => http.delete(`/awards/${id}`).then((r) => r.data),
  setWinner: (id, d) => http.post(`/awards/${id}/winner`, d).then((r) => r.data),
  awardWinners: () => http.get("/awards/winners").then((r) => r.data),
  voteAward: (id, d) => http.post(`/awards/${id}/vote`, d).then((r) => r.data),
  awardVotes: (id) => http.get(`/awards/${id}/votes`).then((r) => r.data),
  celTemplates: () => http.get("/celebration-templates").then((r) => r.data),
  createTemplate: (d) => http.post("/celebration-templates", d).then((r) => r.data),
  deleteTemplate: (id) => http.delete(`/celebration-templates/${id}`).then((r) => r.data),
  celebrationsFeed: () => http.get("/celebrations/feed").then((r) => r.data),

  gamiConfig: () => http.get("/gami/config").then((r) => r.data),
  updateGamiConfig: (d) => http.put("/gami/config", d).then((r) => r.data),
  leaderboard: () => http.get("/gami/leaderboard").then((r) => r.data),
  gamiProfile: (employeeId) => http.get("/gami/profile", { params: { employee_id: employeeId } }).then((r) => r.data),

  kudosFeed: () => http.get("/kudos/feed").then((r) => r.data),
  createKudos: (d) => http.post("/kudos", d).then((r) => r.data),
  kudosMine: (employeeId) => http.get("/kudos/mine", { params: { employee_id: employeeId } }).then((r) => r.data),
  kudosPending: () => http.get("/kudos/pending").then((r) => r.data),
  approveKudos: (id) => http.post(`/kudos/${id}/approve`).then((r) => r.data),
  rejectKudos: (id) => http.post(`/kudos/${id}/reject`).then((r) => r.data),
  deleteKudos: (id) => http.delete(`/kudos/${id}`).then((r) => r.data),

  games: () => http.get("/games").then((r) => r.data),
  createGame: (d) => http.post("/games", d).then((r) => r.data),
  updateGame: (id, d) => http.put(`/games/${id}`, d).then((r) => r.data),
  deleteGame: (id) => http.delete(`/games/${id}`).then((r) => r.data),
  gamesFeed: (employeeId) => http.get("/games/feed", { params: { employee_id: employeeId } }).then((r) => r.data),
  gamePlayData: (id, employeeId) => http.get(`/games/${id}/play`, { params: { employee_id: employeeId } }).then((r) => r.data),
  submitGame: (id, d) => http.post(`/games/${id}/play`, d).then((r) => r.data),
  gameLeaderboard: (id) => http.get(`/games/${id}/leaderboard`).then((r) => r.data),

  communities: () => http.get("/communities").then((r) => r.data),
  communitiesFeed: (employeeId) => http.get("/communities/feed", { params: { employee_id: employeeId } }).then((r) => r.data),
  community: (id) => http.get(`/communities/${id}`).then((r) => r.data),
  createCommunity: (d) => http.post("/communities", d).then((r) => r.data),
  updateCommunity: (id, d) => http.put(`/communities/${id}`, d).then((r) => r.data),
  deleteCommunity: (id) => http.delete(`/communities/${id}`).then((r) => r.data),
  toggleExpert: (id, employeeId) => http.post(`/communities/${id}/expert`, { employee_id: employeeId }).then((r) => r.data),
  communityPosts: (id) => http.get(`/communities/${id}/posts`).then((r) => r.data),
  createPost: (id, d) => http.post(`/communities/${id}/posts`, d).then((r) => r.data),
  commentPost: (pid, d) => http.post(`/posts/${pid}/comment`, d).then((r) => r.data),
  votePost: (pid, d) => http.post(`/posts/${pid}/vote`, d).then((r) => r.data),
  pinPost: (pid) => http.post(`/posts/${pid}/pin`).then((r) => r.data),
  verifyComment: (pid, cid) => http.post(`/posts/${pid}/comments/${cid}/verify`).then((r) => r.data),
  deletePost: (pid) => http.delete(`/posts/${pid}`).then((r) => r.data),
  deleteComment: (pid, cid) => http.delete(`/posts/${pid}/comments/${cid}`).then((r) => r.data),
  communityMessages: (id, after) => http.get(`/communities/${id}/messages`, { params: after ? { after } : {} }).then((r) => r.data),
  sendMessage: (id, d) => http.post(`/communities/${id}/messages`, d).then((r) => r.data),
  deleteMessage: (mid) => http.delete(`/messages/${mid}`).then((r) => r.data),

  kudosNotifications: (employeeId) => http.get("/kudos/notifications", { params: { employee_id: employeeId } }).then((r) => r.data),
  markKudosSeen: (employeeId) => http.post("/kudos/notifications/seen", { employee_id: employeeId }).then((r) => r.data),
  inbox: (employeeId) => http.get("/notifications/inbox", { params: { employee_id: employeeId } }).then((r) => r.data),
  inboxSeen: (employeeId) => http.post("/notifications/inbox/seen", { employee_id: employeeId }).then((r) => r.data),
  profile: (employeeId) => http.get(`/profile/${employeeId}`).then((r) => r.data),
  notifPrefs: (employeeId) => http.get("/notifications/prefs", { params: { employee_id: employeeId } }).then((r) => r.data),
  updateNotifPrefs: (d) => http.put("/notifications/prefs", d).then((r) => r.data),
};
